var resourceInfo={
ids_add_tracker:'Add Tracker',
ids_add_trackertips:'There will be only one administrator for one GPS Tracker. The first user who adds the tracker will be the default administrator priority. The second user or later user will be the attached user who need authorized by administrator.',
ids_administrator_add_tracker:'Administrator add the Tracker',
ids_scan_qr_code:'1. Scan QR Code',
ids_scan_qr_codetips1:'You can find the IMEI QR code on the gift box label, see below shows.',
ids_scan_qr_codetips2:'Then select “I want to add a new tracker” option. Then scan the QR code displays on the gift box label.',
ids_manually_input_iMEI_code:'2. Manually Input IMEI Code',
ids_manually_input_iMEI_codetps:'If there has some problem that cannot scan QR code, you can manually input the IMEI Code for backup.<br/>The IMEI code will display on the tracker product label and gift box label which are 15 numbers:<br/>“IMEI: xxxxxxxxxxxxxxx”.',
ids_second_user_add_tracker:'Second User add tracker',
ids_second_user_add_trackertips:'Select the “I want to follow other tracker”.<br/>Please ask administrator open the invite QR code on the menu “Attached User->”+”” in his/her App.<br/>Then you can scan the Invite QR code to add the tracker.<br/>You will only get limited authorities of the tracker except removing administrator’s tracker.',
ids_main_screen:'Main Screen',
ids_main_screen_help:'The main screen provides buttons to help you monitor your MOVETRACK.',
ids_safe_zone:'Safe Zone',
ids_touch :'Touch ',
ids_to_enter_page:'to set up your safe zones.<br/>You can now define geographical areas called safe zones. When your MOVETRACK leaves one of these zones, you will be notified via the App.',
ids_power_save:'Power Save',
ids_powersave_eithertouching:'Access this page by either touching ',
ids_powersave_eithertouchinghelp:'or from “Settings-> Power Save”. You can adjust the location frequency (every 3, 5, 10, 30 or 60 minutes) and mode (Accurate, Normal or Manual), to achieve your ideal compromise between accuracy and battery life.',
ids_history_location:'History Location',
ids_history_locationman1:'Access this page from “Settings-> History Location”. To view the MOVETRACK\'s location on a particular day/timeline,touch',
ids_history_locationman2:'to specify the date and time range (Start Time and End Time). The map will automatically zoom to show all the recorded locations of your MOVETRACK. Zoom in or out to get a clearer view.',
ids_faq:'FAQ',
ids_faq_guide1:'1. How come I cannot obtain the position of my MOVETRACK?',
ids_faq_guide1tips:'Confirm that data is enabled on your Nano-SIM card.<br/>Check if your Nano-SIM card is inserted correctly in the MOVETRACK\'s SIM slot.<br/>Check your MOVETRACK\'s battery level.<br/>Ensure that your MOVETRACK has access to a clear signal.<br/>Switch your MOVETRACK off and on to restore service.',
ids_faq_guide2:'2. Why does it take so long to find my location?',
ids_faq_guide2tips:'Check which power-saving mode is selected. In manual mode, your MOVETRACK can only find your location when you press the ',
ids_faq_guide2tipsbtn:'button.',
ids_faq_guide2note:'Note: If you enable the Auto change to Manual mode, your MOVETRACK will auto-switch to manual mode once the power level is less than 20%.',
ids_faq_guide3:'3. How many users can monitor my MOVETRACK at the same time?',
ids_faq_guide3tips:'10 users can monitor your MOVETRACK at any one time. You can invite users by sharing the QR code on the Invite User page.',
ids_faq_guide4:'4. Can I make calls to my MOVETRACK?',
ids_faq_guide4tips:'Your MOVETRACK does not support voice calling.',
ids_faq_guide5:'5. What do you use my personal data for?',
ids_faq_guide5tips:'Your personal data will not be used for advertising purposes, unless you have given us your express consent. Moreover, we will not transfer your personal data to any third parties without your express consent. The transfer of personal data to public institutions and public authorities that are entitled to receive such information, will only be carried out to the extent required by law or if we are obliged to do so by virtue of a court order or court ruling. If we commission third parties to provide certain services for us, such third parties will only have limited access to personal data, insofar as this is necessary to provide such services. Such third parties are bound to comply with the applicable data protection laws and our Privacy Policy while processing personal data.'
}