var resourceInfo={
ids_main_screen:'Pantalla principal',
ids_main_screen_help:'La pantalla principal contiene teclas que le ayudan a hacer un seguimiento de su MOVETRACK.',
ids_safe_zone:'Zona segura',
ids_touch :'Toque',
ids_to_enter_page:'para establecer sus zonas seguras.<br/>Aquí puede definir áreas geográficas conocidas como zonas seguras. Cuando su MOVETRACK abandone una de estas zonas, recibirá una notificación a través de la aplicación.',
ids_power_save:'Ahorro de energía',
ids_powersave_eithertouching:'Acceda a esta página tocando',
ids_powersave_eithertouchinghelp:'o bien en "Ajustes-> Ahorro de energía". Puede ajustar la frecuencia de localización (cada 3, 5, 10, 30 o 60 minutos) y el modo (preciso, normal o manual) para lograr el comportamiento ideal entre precisión y duración de la batería.',
ids_history_location:'Historial de localización',
ids_history_locationman1:'Acceda a esta página desde "Ajustes-> Historial de localización". Para ver las ubicaciones en las que se localizó el MOVETRACK en un día o lapso de tiempo determinados, toque',
ids_history_locationman2:'y especifique la fecha y el intervalo de tiempo (hora de inicio y de fin). El mapa se acercará automáticamente para mostrarle todas las ubicaciones registradas de su MOVETRACK. Puede acercar o alejar la imagen para verla mejor.',
ids_faq:'Preguntas frecuentes',
ids_faq_guide1:'1. ¿Por qué no puedo obtener la posición de mi MOVETRACK?',
ids_faq_guide1tips:'Confirme que los datos están activados en su tarjeta SIM nano.<br/>Compruebe si la tarjeta SIM nano está insertada correctamente en la ranura para SIM del MOVETRACK.<br/>Compruebe el nivel de batería de su MOVETRACK.<br/>Asegúrese de que el MOVETRACK tenga buena cobertura.<br/>Apague y vuelva a encender el MOVETRACK para restaurar el servicio.',
ids_faq_guide2:'2. ¿Por qué MOVETRACK tarda tanto en encontrar mi ubicación?',
ids_faq_guide2tips:'Compruebe qué modo de ahorro de energía tiene seleccionado. En el modo manual, MOVETRACK sólo puede encontrar su ubicación cuando pulsa el botón',
ids_faq_guide2tipsbtn:'&nbsp;.',
ids_faq_guide2note:'Nota: Si activa la opción Cambiar automáticamente a modo manual, MOVETRACK pasará al modo manual automáticamente cuando le quede menos del 20 % de batería.',
ids_faq_guide3:'3. ¿Cuántos usuarios pueden hacer un seguimiento de mi MOVETRACK al mismo tiempo?',
ids_faq_guide3tips:'Pueden rastrear el MOVETRACK hasta 10 usuarios a la vez. Puede invitar a usuarios compartiendo el código QR de la página Invitar a usuario.',
ids_faq_guide4:'4. ¿Puedo realizar llamadas al MOVETRACK?',
ids_faq_guide4tips:'No, MOVETRACK no admite llamadas de voz.',
ids_faq_guide5:'5. ¿Para qué se utilizan mis datos personales?',
ids_faq_guide5tips:'Sus datos personales no se utilizarán con fines publicitarios, a no ser que nos haya dado su consentimiento de forma explícita. De igual forma, tampoco compartiremos sus datos personales con terceros sin su consentimiento explícito. Los datos personales sólo se comunicarán a las instituciones y autoridades públicas que tienen derecho a recibir este tipo de información en la medida en que lo exija la ley, o si nos vemos obligados a hacerlo en virtud de una orden o resolución judicial. Si contratamos a terceros para que nos proporcionen algún tipo de servicio, estos sólo tendrán acceso limitado a los datos personales, en la medida en que dicho acceso sea necesario para proporcionar tales servicios. Cuando procesen datos personales, estos terceros estarán obligados a cumplir las leyes vigentes de protección de datos y nuestra Política de privacidad.'
}